# General Settings
name: Scott McCulloch
title: Scott McCulloch - Senior Software Engineer
job_title: Software Engineer
email: smcculloch@gmail.com
description: I'm a web coder that enjoys sport, gaming and listening to music. You can find me on Twitter or LinkedIn below.
avatar: /images/scott-mcculloch.jpg
favicon: /favicon.ico
twitter_handler: sj_mcculloch
analytics_code: 
disqus: smcculloch

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: 'http://twitter.com/sj_mcculloch' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/sjmcculloch/' }
-  { name: skype, url: '' }
-  { name: github, url: '' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: 'https://stackoverflow.com/users/1536793/scott-mcculloch' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: ""
baseurl: ""
shareurl: "https://www.smcculloch.com"

# Includes
include: ["_pages", "_redirects"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

  